package org.banco.vistas;

import javax.swing.table.DefaultTableModel;
import org.banco.servicios.DatosWidgets;

public final class Principal extends javax.swing.JPanel {

    private final DefaultTableModel dtm;
    private final DatosWidgets dw;
    
    private String simboloMoneda = "S/";

    public Principal() {
        initComponents();
        dtm = (DefaultTableModel) tClientesRecientes.getModel();
        initStyles();

        dw = new DatosWidgets();
        labelSimbolo.setText(simboloMoneda);
        
        cargarDatosWidgets();
    }

    private void initStyles() {
        txtTitulo.putClientProperty("FlatLaf.styleClass", "h0");
        labelClientes.putClientProperty("FlatLaf.styleClass", "h3");
        label.putClientProperty("FlatLaf.styleClass", "h3");
        txtOperaciones.putClientProperty("FlatLaf.styleClass", "h3");
        txtSaldo.putClientProperty("FlatLaf.styleClass", "h3");
        tClientesRecientes.setShowVerticalLines(true);
        
        widClientes.putClientProperty("FlatLaf.style", "arc: 30");
        widCuentas.putClientProperty("FlatLaf.style", "arc: 30");
        widOperaciones.putClientProperty("FlatLaf.style", "arc: 30");
        widSaldo.putClientProperty("FlatLaf.style", "arc: 30");
        btnSimboloPanel.putClientProperty("FlatLaf.style", "arc: 70");
        
        tClientesRecientes.putClientProperty("Table.alternateRowColor", true);

    }

    public void cargarDatosWidgets() {
        dw.cargarClientesWidgets(labelNumClientes);
        dw.cargarCuentasWidgets(labelNumCuentas);
        dw.cargarOperacionesWidgets(labelNumOperaciones);
        dw.cargarSaldoWidgets(labelNumSaldo, labelSimbolo);
        dw.ponerUltimosClientesTabla(dtm);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        widCuentas = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        labelNumCuentas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        widSaldo = new javax.swing.JPanel();
        txtSaldo = new javax.swing.JLabel();
        labelNumSaldo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSimboloPanel = new javax.swing.JPanel();
        labelSimbolo = new javax.swing.JLabel();
        widOperaciones = new javax.swing.JPanel();
        txtOperaciones = new javax.swing.JLabel();
        labelNumOperaciones = new javax.swing.JLabel();
        widClientes = new javax.swing.JPanel();
        labelClientes = new javax.swing.JLabel();
        labelNumClientes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jscrollUltimosClientes = new javax.swing.JScrollPane();
        tClientesRecientes = new javax.swing.JTable();
        txtTitulo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(799, 435));
        setLayout(null);

        widCuentas.setBackground(new java.awt.Color(245, 121, 0));
        widCuentas.setPreferredSize(new java.awt.Dimension(155, 145));

        label.setForeground(new java.awt.Color(0, 0, 0));
        label.setText("Total de cuentas");

        labelNumCuentas.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelNumCuentas.setForeground(new java.awt.Color(51, 51, 51));
        labelNumCuentas.setText("28");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Registrados");

        javax.swing.GroupLayout widCuentasLayout = new javax.swing.GroupLayout(widCuentas);
        widCuentas.setLayout(widCuentasLayout);
        widCuentasLayout.setHorizontalGroup(
            widCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(widCuentasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(widCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(widCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addComponent(labelNumCuentas, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        widCuentasLayout.setVerticalGroup(
            widCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(widCuentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNumCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        widSaldo.setBackground(new java.awt.Color(245, 121, 0));

        txtSaldo.setForeground(new java.awt.Color(0, 0, 0));
        txtSaldo.setText("Saldo total");

        labelNumSaldo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNumSaldo.setForeground(new java.awt.Color(51, 51, 51));
        labelNumSaldo.setText("83k");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("De todas las cuentas");

        btnSimboloPanel.setBackground(new java.awt.Color(245, 121, 0));
        btnSimboloPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimboloPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimboloPanelMouseClicked(evt);
            }
        });

        labelSimbolo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelSimbolo.setForeground(new java.awt.Color(51, 51, 51));
        labelSimbolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSimbolo.setText("S/");
        labelSimbolo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btnSimboloPanelLayout = new javax.swing.GroupLayout(btnSimboloPanel);
        btnSimboloPanel.setLayout(btnSimboloPanelLayout);
        btnSimboloPanelLayout.setHorizontalGroup(
            btnSimboloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSimboloPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(labelSimbolo)
                .addGap(14, 14, 14))
        );
        btnSimboloPanelLayout.setVerticalGroup(
            btnSimboloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSimboloPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelSimbolo))
        );

        javax.swing.GroupLayout widSaldoLayout = new javax.swing.GroupLayout(widSaldo);
        widSaldo.setLayout(widSaldoLayout);
        widSaldoLayout.setHorizontalGroup(
            widSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, widSaldoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimboloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, widSaldoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(widSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(widSaldoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(labelNumSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        widSaldoLayout.setVerticalGroup(
            widSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(widSaldoLayout.createSequentialGroup()
                .addGroup(widSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(widSaldoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSimboloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNumSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(22, 22, 22))
        );

        widOperaciones.setBackground(new java.awt.Color(245, 121, 0));

        txtOperaciones.setForeground(new java.awt.Color(0, 0, 0));
        txtOperaciones.setText("Operaciones hoy");

        labelNumOperaciones.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelNumOperaciones.setForeground(new java.awt.Color(51, 51, 51));
        labelNumOperaciones.setText("33");

        javax.swing.GroupLayout widOperacionesLayout = new javax.swing.GroupLayout(widOperaciones);
        widOperaciones.setLayout(widOperacionesLayout);
        widOperacionesLayout.setHorizontalGroup(
            widOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(widOperacionesLayout.createSequentialGroup()
                .addGroup(widOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(widOperacionesLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(labelNumOperaciones))
                    .addGroup(widOperacionesLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        widOperacionesLayout.setVerticalGroup(
            widOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(widOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelNumOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        widClientes.setBackground(new java.awt.Color(245, 121, 0));

        labelClientes.setForeground(new java.awt.Color(0, 0, 0));
        labelClientes.setText("Total de clientes");

        labelNumClientes.setBackground(new java.awt.Color(51, 51, 51));
        labelNumClientes.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelNumClientes.setForeground(new java.awt.Color(51, 51, 51));
        labelNumClientes.setText("23");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registrados");

        javax.swing.GroupLayout widClientesLayout = new javax.swing.GroupLayout(widClientes);
        widClientes.setLayout(widClientesLayout);
        widClientesLayout.setHorizontalGroup(
            widClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(widClientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(widClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(labelNumClientes))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        widClientesLayout.setVerticalGroup(
            widClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(widClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNumClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tClientesRecientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", " Nombres", "Tipo Cuenta", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jscrollUltimosClientes.setViewportView(tClientesRecientes);

        txtTitulo.setText("Clientes Recientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(widOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(widClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(widCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(widSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jscrollUltimosClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(widCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(widClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(widSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(widOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jscrollUltimosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 435);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimboloPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimboloPanelMouseClicked
        simboloMoneda = "S/".equals(simboloMoneda) ? "$" : "S/";
        labelSimbolo.setText(simboloMoneda);
        dw.cargarSaldoWidgets(labelNumSaldo, labelSimbolo);
    }//GEN-LAST:event_btnSimboloPanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnSimboloPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jscrollUltimosClientes;
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelClientes;
    private javax.swing.JLabel labelNumClientes;
    private javax.swing.JLabel labelNumCuentas;
    private javax.swing.JLabel labelNumOperaciones;
    private javax.swing.JLabel labelNumSaldo;
    private javax.swing.JLabel labelSimbolo;
    private javax.swing.JTable tClientesRecientes;
    private javax.swing.JLabel txtOperaciones;
    private javax.swing.JLabel txtSaldo;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JPanel widClientes;
    private javax.swing.JPanel widCuentas;
    private javax.swing.JPanel widOperaciones;
    private javax.swing.JPanel widSaldo;
    // End of variables declaration//GEN-END:variables
}
